[package]
name = "image_processor"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
clap.workspace = true
image.workspace = true
libloading.workspace = true
thiserror.workspace = true
log.workspace = true
env_logger.workspace = true
plugin_interface.workspace = true

[dev-dependencies]
tempfile = "3"
